ProjectBusinessCustomer/Controllers/CustomerController.cs
using ProjectBusinessCustomer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace ProjectBusinessCustomer.Controllers
{
    public class CustomerController : Controller
    {
        public MyDbContext myDbContext = new MyDbContext();
        public CustomerController()
        {

        }
        public CustomerController(MyDbContext db)
        {
            this.myDbContext = db;
        }
        // GET: Customer
        public ActionResult Customers()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", new RouteValueDictionary(new { controller = "Account", action = "Login" }));
            }
            IEnumerable<Customer> customers =
                 myDbContext.
                 Customers
                 .ToList();
            return View("Customers", customers);
        }
        public ActionResult FormCustomer()
        {
            Customer c = new Customer();
            IEnumerable<Society> societies = myDbContext.Societies.ToList(); // récuperer la liste des societies pour avoir une liste déroulante
            ViewBag.Societies = societies;// et  le stocker dans le modéle
            return View("FormCustomer", c);
        }
        [HttpPost]
        public ActionResult SaveCustomer(Customer c)
        {
            IEnumerable<Society> societies = myDbContext.Societies.ToList();// récuperer la liste des societies pour avoir une liste déroulante
            ViewBag.Societies = societies;// et  le stocker dans le modéle
            if (ModelState.IsValid)
            {
                myDbContext.Customers.Add(c);
                myDbContext.SaveChanges();
            }

            return View("FormCustomer", c);
        }

        public ActionResult Delete(int CustomerID)
        {

            Customer customer = myDbContext.Customers.Where(c => c.CustomerID == CustomerID).FirstOrDefault();
            myDbContext.Customers.Remove(customer);
            myDbContext.SaveChanges();
            IEnumerable<Customer> customerUpdate = myDbContext.Customers.ToList();
            return View("Customers", customerUpdate);
        }

        public ActionResult Edit(int CustomerID)
        {
            Customer customer = myDbContext.Customers.FirstOrDefault(c => c.CustomerID == CustomerID);
            IEnumerable<Society> societies = myDbContext.Societies.ToList();
            ViewBag.Societies = societies;
            return View(customer);
        }

        [HttpPost]
        public ActionResult Edit(Customer c)
        {
            IEnumerable<Society> societies = myDbContext.Societies.ToList();
            ViewBag.Societies = societies;
            if (ModelState.IsValid)
            {
                Customer customer = myDbContext.Customers.FirstOrDefault(x => x.CustomerID == c.CustomerID);
                customer.CustomerName = c.CustomerName;
                customer.Profile = c.Profile;
                customer.Country = c.Country;
                customer.Region = c.Region;
                customer.Address = c.Address;
                customer.Email = c.Email;
                customer.Phone = c.Phone;
                customer.Fax = c.Fax;
                customer.Activity = c.Activity;
                customer.ImportantNotes = c.ImportantNotes;
                customer.SocietyID = c.SocietyID;
                myDbContext.SaveChanges();
            }
            return View();
        }
    }
}

ProjectBusinessCustomer/Controllers/ProjectController.cs
using ProjectBusinessCustomer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace ProjectBusinessCustomer.Controllers
{
    public class ProjectController : Controller
    {
        ExecuteQuery Query = new ExecuteQuery();
        MyDbContext MyDbContext = new MyDbContext();
        public string endPoint = "https://inlsprl.visualstudio.com/DefaultCollection/_apis/projects?stateFilter=All";
        // GET: Project
        public ActionResult Projects()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", new RouteValueDictionary(new { controller = "Account", action = "Login" }));
            }
            List<Project> list = Query.GetProjects(endPoint);
            Query.synchronisationProject(list);
            List<Project> projects = MyDbContext.Projects.ToList();
            return View(projects);
        }

        public ActionResult Details(int ProjectID)
        {
            Project project = MyDbContext.Projects.FirstOrDefault(p => p.ProjectID == ProjectID);
            return View(project);
        }

        [HttpPost]
        public ActionResult Details(Project p)
        {
                Project project = MyDbContext.Projects.Where(x => x.ProjectID == p.ProjectID).FirstOrDefault();
                MyDbContext.SaveChanges();
              return View();
        }
    }
}

ProjectBusinessCustomer/Controllers/SocietyController.cs
using ProjectBusinessCustomer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace ProjectBusinessCustomer.Controllers
{
   
    public class SocietyController : Controller
    {
        public MyDbContext myDbContext = new MyDbContext();
        public SocietyController()
        {

        }
        public SocietyController(MyDbContext db)
        { 
            this.myDbContext = db;
        }

        // GET: Society

        public ActionResult Societies()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", new RouteValueDictionary(new { controller = "Account", action = "Login" }));
            }
            IEnumerable<Society> societies = myDbContext.Societies.ToList();
            return View("Societies", societies);
        }

        public ActionResult FormSociety()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveSociety(Society s)
        {
            if (ModelState.IsValid)
            {
                myDbContext.Societies.Add(s);
                myDbContext.SaveChanges();

            }
            return View("FormSociety", s);
        }

        public ActionResult Delete(int SocietyID)
        {
            Society society = myDbContext.Societies.FirstOrDefault(s => s.SocietyID == SocietyID);
            if (society != null)
            {
                myDbContext.Societies.Remove(society);
                myDbContext.SaveChanges();
            }
            IEnumerable<Society> societiesUpdate = myDbContext.Societies.ToList();
            return View("Societies", societiesUpdate);
        }
        public ActionResult Edit(int SocietyID)
        {
            Society society = myDbContext.Societies.FirstOrDefault(s => s.SocietyID == SocietyID);
            return View(society);
        }
        [HttpPost]
        public ActionResult Edit(Society s)
        {
            if (ModelState.IsValid)
            {
                Society society = myDbContext.Societies.Where(x => x.SocietyID == s.SocietyID).FirstOrDefault();
                society.SocietyName = s.SocietyName;
                society.CompanySocial = s.CompanySocial;
                society.SocietyAddress = s.SocietyAddress;
                society.SocietyEmail = s.SocietyEmail;
                society.SocietyPhone = s.SocietyPhone;
                society.WebSite = s.WebSite;
                society.SocietyFax = s.SocietyFax;
                myDbContext.SaveChanges();
            }
            return View();
        }

        public ActionResult Details(int SocietyID)
        {
            Society society = myDbContext.Societies.FirstOrDefault(s => s.SocietyID == SocietyID);

            IEnumerable<Society_Projects> society_Projects = from sp in myDbContext.Society_Projects.ToList()
                                                             where
                                                             sp.SocietyID == SocietyID
                                                             select sp;


                    IEnumerable<Project> Allprojects = myDbContext.Projects.ToList();
                    var projects =
                             from p in Allprojects
                             join sp in society_Projects on p.ProjectID equals sp.ProjectID
                             select p;

            ViewBag.Projects = projects;
            return View(society);
        }



        public ActionResult FormProject(int SocietyID)
        {
            Society society = myDbContext.Societies.FirstOrDefault(s => s.SocietyID == SocietyID);
            ViewBag.Projects = myDbContext.Projects.ToList();
            TempData["SocietyID"] = SocietyID.ToString();
            return View(society);
        }
        [HttpPost]
        public ActionResult SaveProject(int ProjectID)
        {
            int idSociete = int.Parse(TempData["SocietyID"].ToString());
            if (!myDbContext.Society_Projects.Any(s => s.ProjectID == ProjectID && s.SocietyID == idSociete))
            {
                Society_Projects society_Projects = new Society_Projects();

                society_Projects.ProjectID = ProjectID;
                society_Projects.SocietyID = idSociete;
                myDbContext.Society_Projects.Add(society_Projects);
                myDbContext.SaveChanges();
            }
            ViewBag.Projects = myDbContext.Projects.ToList();
            return RedirectToAction("Societies");
        }
        
        public ActionResult Remove(int ProjectID)
        {
            Society_Projects society_Project = myDbContext.Society_Projects.FirstOrDefault(s => s.ProjectID == ProjectID);
            if(society_Project != null)
            {
                myDbContext.Society_Projects.Remove(society_Project);
                myDbContext.SaveChanges();

            }

            IEnumerable<Society_Projects> society_Projects = from sp in myDbContext.Society_Projects.ToList()
                                                             where
                                                             sp.SocietyID == society_Project.SocietyID
                                                             select sp;


            IEnumerable<Project> Allprojects = myDbContext.Projects.ToList();
            var projects =
                     from p in Allprojects
                     join sp in society_Projects on p.ProjectID equals sp.ProjectID
                     select p;

            ViewBag.Projects = projects;

            
            Society society = myDbContext.Societies.FirstOrDefault(s => s.SocietyID == society_Project.SocietyID);
            return View("Details", society);
        }
    }
}

ProjectBusinessCustomer/Controllers/WorkItemController.cs
using ProjectBusinessCustomer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Microsoft.AspNet.Identity;
using System.Security.Claims;

namespace ProjectBusinessCustomer.Controllers
{
    public class WorkItemController : Controller
    {
        ExecuteQuery Query = new ExecuteQuery();
        MyDbContext myDbContext = new MyDbContext();
        private ApplicationDbContext db = new ApplicationDbContext();
        public WorkItemController()
        {

        }
        public WorkItemController(MyDbContext db)
        {
            this.myDbContext = db;
        }
        public WorkItemController(MyDbContext db, ExecuteQuery query)
        {
            this.myDbContext = db;
            this.Query = query;
        }
        // GET: WorkItem
        public ActionResult Tasks()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", new RouteValueDictionary(new { controller = "Account", action = "Login" }));
            }
            Query.synchronisation();
            IEnumerable<Project> projects = myDbContext.Projects.ToList();// récuperer la liste des projets pour avoir une liste déroulante
            ViewBag.Projects = projects;// et  le stocker dans le modéle
            List<Task> tasks = myDbContext.Tasks.ToList();
           
            
            //string currentUserId = User.Identity.GetUserId();
            //ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            //string userName = currentUser.Email;
            //IEnumerable<Task> tasksassignee = from t in tasks
            //                                               where
            //                                               t.userEmail == currentUser.Email
            //                           select t;
            return View(tasks);
        }
        public ActionResult Synchronisation()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", new RouteValueDictionary(new { controller = "Account", action = "Login" }));
            }
            ViewBag.Projects = myDbContext.Projects.ToList();
            ViewBag.Name = new SelectList(myDbContext.Projects.ToList(), "Name", "Name");

            return View();
        }
        [HttpPost]
        public ActionResult Synchronisation(UserToken model)
        {
            UserToken userToken = new UserToken();
            //ViewBag.Projects = myDbContext.Projects.ToList();
            //ViewBag.Name = new SelectList(myDbContext.Projects.ToList(), "Name", "Name");
            if (ModelState.IsValid)
            {
                userToken.Uri = model.Uri;
                userToken.Token = model.Token;
                userToken.Projectname = model.Projectname;   
                //myDbContext.Tokens.Add(userToken);
                //myDbContext.SaveChanges();
                ExecuteQuery query = new ExecuteQuery(userToken.Uri, userToken.Token, userToken.Projectname);
                
                query.synchronisation();
                return RedirectToAction("tasks");

            }
            else
            {
                return View();
            }
            
           
        }
    }
}

ProjectBusinessCustomer/Views/Shared/RefView.cshtml
@model TimeSheetNS.Repositorys.Models.TimeSheet

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TimeSheet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.DateCeation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCeation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCeation, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Userame, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Userame, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Userame, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Project, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Project, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Task, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Task, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Task, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" id="datetimepicker1">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group" id="datetimepicker2">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.isbillable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isbillable)
                    @Html.ValidationMessageFor(model => model.isbillable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
        $(document).ready(function ()
        {
            $("#datetimepicker1 , #datetimepicker2").datetimepicker(
                {
                    defaultDate: '@DateTime.Now',
                    showTodayButton: true,
                    format: 'DD/MM/YYYY HH:mm',
                    showClose: true,
                    showClear: true,
                    toolbarPlacement: 'top',
                    stepping: 15
                });
        });
</script>
}

ProjectBusinessCustomer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/select2.min.css" rel="stylesheet" />
    <link href="~/Content/select2-bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("employées", "Customers", "Customer", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("sociétés", "Societies", "Society", new { area = "" }, new { @class = "navbar-brand" })
                    @*@Html.ActionLink("tâches", "Tasks", "WorkItem", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("projets", "Projects", "Project", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("synchronisation", "Synchronisation", "WorkItem", new { area = "" }, new { @class = "navbar-brand" })*@
                }
                else
                {
                    <span class="navbar-brand">BusinessCustomer</span>
                }

            </div>
            <div class="navbar-buttons navbar-header pull-right" role="navigation">
                @Html.Partial("_LoginPartial")
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/select2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.js-example-basic-single').select2({
                placeholder: ' -- Select Project--'
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

ProjectBusinessCustomer/Views/Shared/_Layout_Back.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

ProjectBusinessCustomer/Views/Shared/_MSGraphLoginPartial.cshtml
<!--  Copyright (c) Microsoft. All rights reserved. Licensed under the MIT license.
        See LICENSE in the source repository root for complete license information. -->
@using Resources
@if (Request.IsAuthenticated)
{
    <text>
        <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">
                @*The 'preferred_username' claim can be used for showing the user's primary way of identifying themselves.*@
                Hello, @Session["UserName"] @*@(System.Security.Claims.ClaimsPrincipal.Current.FindFirst("preferred_username")?.Value)*@

            </li>
            <li>
                @Html.ActionLink(Resource.SignOut, "SignOut", "Account")
            </li>
        </ul>
    </text>
}
else
{
    <style type="text/css">

        ul.links {
            list-style-type: none;
        }

            ul.links li {
                display: inline-block;
                border-left: 1px solid black;
                padding-left: 10px;
                margin-left: 10px;
            }

                ul.links li:first-child {
                    border-left: 0;
                    padding-left: 0;
                    margin-left: 0;
                }
    </style>

    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="@Url.Action("SignIn", "Account")" title="Sign in" class="links">
                @Resource.SignIn
            </a>
        </li>
    </ul>
}